### ISSUE TITLE
I would like to use this but there are no examples

### ISSUE THREAD

**Issue by clarkezone** [freeformz/ansible#1]
I've never used an inventory plugin hence no clue how to use this, please consider giving an e2e example eg how to set an public sshkey on a set of hosts in my tailnet

**Comment by freeformz** [comment]
I can add some over the next few days.

**Comment by freeformz** [comment]
Is [this](https://github.com/freeformz/ansible/blob/0993e1e02415da1fe5a5b74c7b33cf16526e4e52/README.md) sufficient?

If not what information would you like to see in an example that is currently missing?

**Comment by freeformz** [comment]
Decided to do [another update](https://github.com/freeformz/ansible/blob/531197d5364121b2e10a5ecd63ee79bd66459957/README.md) after that.

**Comment by freeformz** [comment]
I'm going to close this as I believe it to be done. If you feel the existing examples aren't sufficient, please open a new ticket and detail what you would like shown. Thanks!

**Comment by clarkezone** [comment]
Thanks, this looks good, i'll give it a try next time I'm updating my homelab install process
